version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.15.0
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master
  post-deploy:
    docker:
      - image: foosoftware/lighthouse-check:latest
    steps:
      - checkout
      - run:
          name: Run Lighthouse audits and save results
          command: |
            mkdir /tmp/artifacts
            lighthouse-check --verbose \
              --author $CIRCLE_USERNAME \
              --awsAccessKeyId $AWS_ACCESS_KEY_ID \
              --awsBucket $AWS_BUCKET \
              --awsRegion $AWS_REGION \
              --awsSecretAccessKey $AWS_SECRET_ACCESS_KEY \
              --branch $CIRCLE_BRANCH \
              --configFile ./lighthouse-check.json \
              --outputDirectory /tmp/artifacts \
              --pr $CIRCLE_PULL_REQUEST \
              --sha $CIRCLE_SHA1 \
              --slackWebhookUrl $SLACK_WEBHOOK_URL \
      - store_artifacts:
          path: /tmp/artifacts

workflows:
  version: 2
  test-deploy-post-deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
      - post-deploy:
          requires:
            - deploy
